import { ALL_PERMISSIONS, type PermissionKey } from "./permissions";

export const SYSTEM_ROLE_SLUGS = {
  SUPER_ADMIN: "super_admin",
  CLINIC_OWNER: "clinic_owner",
  DENTIST: "dentist",
  RECEPTIONIST: "receptionist",
  DENTAL_ASSISTANT: "dental_assistant",
  ACCOUNTANT: "accountant",
  LAB_TECHNICIAN: "lab_technician",
} as const;

export type SystemRoleSlug = (typeof SYSTEM_ROLE_SLUGS)[keyof typeof SYSTEM_ROLE_SLUGS];

export interface SystemRole {
  slug: SystemRoleSlug;
  name: string;
  description: string;
  isSystem: boolean;
  /** scoped to a clinic (false = platform-level, super admin only) */
  isPlatform: boolean;
  permissions: PermissionKey[];
}

const clinicAll = [
  "auth.view",
  "auth.manage",
  "clinic.view",
  "clinic.update",
  "clinic.manage",
  "users.view",
  "users.create",
  "users.update",
  "users.delete",
  "roles.view",
  "roles.manage",
  "patients.view",
  "patients.create",
  "patients.update",
  "patients.delete",
  "patients.export",
  "history.view",
  "history.update",
  "teeth.view",
  "teeth.update",
  "treatments.view",
  "treatments.create",
  "treatments.update",
  "treatments.delete",
  "treatmentPlans.view",
  "treatmentPlans.create",
  "treatmentPlans.update",
  "appointments.view",
  "appointments.create",
  "appointments.update",
  "appointments.delete",
  "queue.manage",
  "prescriptions.view",
  "prescriptions.create",
  "prescriptions.update",
  "billing.view",
  "billing.create",
  "billing.update",
  "billing.delete",
  "payments.view",
  "payments.create",
  "payments.refund",
  "inventory.view",
  "inventory.manage",
  "lab.view",
  "lab.manage",
  "documents.view",
  "documents.upload",
  "documents.delete",
  "recalls.view",
  "recalls.manage",
  "leads.view",
  "leads.manage",
  "expenses.view",
  "expenses.manage",
  "reports.view",
  "reports.export",
  "settings.manage",
] satisfies PermissionKey[];

export const SYSTEM_ROLES: Record<SystemRoleSlug, SystemRole> = {
  super_admin: {
    slug: "super_admin",
    name: "Super Admin",
    description: "Platform-level administrator",
    isSystem: true,
    isPlatform: true,
    permissions: ALL_PERMISSIONS,
  },
  clinic_owner: {
    slug: "clinic_owner",
    name: "Clinic Owner",
    description: "Full access to a single clinic",
    isSystem: true,
    isPlatform: false,
    permissions: clinicAll,
  },
  dentist: {
    slug: "dentist",
    name: "Dentist",
    description: "Clinical care, treatment planning and dental records",
    isSystem: true,
    isPlatform: false,
    permissions: [
      "auth.view",
      "clinic.view",
      "patients.view",
      "patients.create",
      "patients.update",
      "history.view",
      "history.update",
      "teeth.view",
      "teeth.update",
      "treatments.view",
      "treatments.create",
      "treatments.update",
      "treatmentPlans.view",
      "treatmentPlans.create",
      "treatmentPlans.update",
      "appointments.view",
      "appointments.create",
      "appointments.update",
      "prescriptions.view",
      "prescriptions.create",
      "prescriptions.update",
      "billing.view",
      "payments.view",
      "documents.view",
      "documents.upload",
      "recalls.view",
      "recalls.manage",
      "reports.view",
    ],
  },
  receptionist: {
    slug: "receptionist",
    name: "Receptionist",
    description: "Front desk, appointments, queue and patient intake",
    isSystem: true,
    isPlatform: false,
    permissions: [
      "auth.view",
      "clinic.view",
      "patients.view",
      "patients.create",
      "patients.update",
      "appointments.view",
      "appointments.create",
      "appointments.update",
      "queue.manage",
      "billing.view",
      "billing.create",
      "payments.view",
      "payments.create",
      "documents.view",
      "documents.upload",
      "recalls.view",
      "recalls.manage",
      "leads.view",
      "leads.manage",
    ],
  },
  dental_assistant: {
    slug: "dental_assistant",
    name: "Dental Assistant",
    description: "Supports clinical staff, chairs and instruments",
    isSystem: true,
    isPlatform: false,
    permissions: [
      "auth.view",
      "clinic.view",
      "patients.view",
      "appointments.view",
      "queue.manage",
      "teeth.view",
      "treatments.view",
      "documents.view",
      "documents.upload",
      "inventory.view",
      "lab.view",
    ],
  },
  accountant: {
    slug: "accountant",
    name: "Accountant",
    description: "Billing, payments, expenses and financial reports",
    isSystem: true,
    isPlatform: false,
    permissions: [
      "auth.view",
      "clinic.view",
      "patients.view",
      "billing.view",
      "billing.create",
      "billing.update",
      "payments.view",
      "payments.create",
      "payments.refund",
      "inventory.view",
      "expenses.view",
      "expenses.manage",
      "reports.view",
      "reports.export",
    ],
  },
  lab_technician: {
    slug: "lab_technician",
    name: "Lab Technician",
    description: "Dental laboratory case management",
    isSystem: true,
    isPlatform: false,
    permissions: [
      "auth.view",
      "clinic.view",
      "patients.view",
      "appointments.view",
      "lab.view",
      "lab.manage",
      "inventory.view",
      "documents.view",
    ],
  },
};

export const SYSTEM_ROLES_LIST = Object.values(SYSTEM_ROLES);
